### PR TITLE
Remove matplotlib rc overrides.

### PR DESCRIPTION
**Pull request by fperez**
Addresses https://github.com/ipython/ipython/issues/10383.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Just a quick comment to say that this is quite handy for us in Spyder, so I hope it's not removed in the future. I'm fine with leaving it empty though because we can fill it on our side.

**Comment by fperez** [comment]
Agreed @ccordoba12 - I didn't intend to remove b/c I figured someone out there would be likely to use it, but I've added clarifying language both in the help string and comments to this effect, so down the road nobody has the temptation to "clean up"  and nuke it. Thx for the feedback!

**Comment by ccordoba12** [comment]
Great! Thanks for adding that extra comment @fperez!

To give a bit more context, the thing is we make heavy use of the inline backend because we have a dedicated pane to display figures that come from it:

http://docs.spyder-ide.org/current/panes/plots.html

**Comment by fperez** [comment]
Makes sense, that's an excellent use case and it provides great UX. Thanks for the extra context!

**Review by tacaswell — APPROVED** [review]

**Comment by fperez** [comment]
Given [this is now being reported by other mpl users](https://github.com/matplotlib/matplotlib/issues/23007), and @tacaswell's approval (thx!) I'm inclined to merge this.

Unless someone has a reason not to in the next day or two, I'm happy to do it. I haven't touched our actual code in ages so I don't want to step on anyone's toes, but I'll take silence as acquiescence :)

Once merged, it would be nice to cut a release in the next few weeks - I have a class coming up in the fall (as will many others) with over 1,000 students where this has caused headaches in the past, would be nice to not have to deal with it.

**Comment by juanitorduz** [comment]
It would be great to have a new release to be able to use `matplotlib > 3.5.1` :) Thanks !

**Comment by fperez** [comment]
@juanitorduz can you clarify your comment? Is there a version-specific issue with matplotlib you refer to? We do want to make a release b/c of these other issues, but I'm using mpl 3.5.3 just fine, so I'd like to understand what you're referring to...

**Comment by tacaswell** [comment]
I think @juanitorduz is asking for a release of matplotilb-inline with this PR in it.

**Comment by fperez** [comment]
Ah, ok, fair enough - that's [indeed the plan :)](https://github.com/ipython/matplotlib-inline/issues/16).

**Comment by juanitorduz** [comment]
> I think @juanitorduz is asking for a release of matplotilb-inline with this PR in it.

Exactly 😅 ! Thank you for the info! 🚀

**Comment by fperez** [comment]
@juanitorduz - all set; in #16 we're finalizing the details, but I should have this up soon on PyPI. Thanks for the nudge :)

**Comment by mgeier** [comment]
Thanks @fperez for removing those RC overrides! I have suffered from them for years (see e.g. https://github.com/ipython/ipykernel/issues/267#issuecomment-441069321), even more so now that local `ipython_kernel_config.py` files are not supported anymore (https://github.com/ipython/ipython/issues/13663).

With the latest `matplotlib-inline` it is finally possible to use `matplotlibrc` files, which is great!

The `figure.dpi` setting is still wrong by default (for notebooks), but at least now it is much closer to the correct value (100 vs. 96). And now it's easy to fix this with a `matplotlibrc` containing `figure.dpi: 96`.

**Comment by mgeier** [comment]
Could the wrong `figure.dpi` be fixed by default via a Matplotlib theme, see https://github.com/ipython/ipython/issues/9710?

**Comment by fperez** [comment]
@mgeier - given we are not expliciltly setting the figure dpi anywhere anymore, and that I don't think we should embark on a custom theme, do you have any further thoughts on what we should do from our (as in iptyhon/mpl-inline) end on this? 

If so, please go ahead and open a new issue on this so we can look into it. And thanks for your input on all these related issues!

**Comment by mgeier** [comment]
> do you have any further thoughts on what we should do from our (as in iptyhon/mpl-inline) end on this?

I still think that it would be great if `figure.dpi` could somehow be 96 by default. But I don't know how this could be achieved. Maybe that's not feasible at all.

For now, I'm fine with manually creating a `matplotlibrc` file, which I've documented there:

* https://nbsphinx.readthedocs.io/en/latest/code-cells.html#Plots
* https://nbviewer.org/github/mgeier/python-audio/blob/master/plotting/matplotlib-inline-defaults.ipynb

**Pull request merged**
