### PR TITLE
Do not enable default Matplotlib backend when checking what the backend is

### LINKED ISSUE #37: Do not automatically resolve default Matplotlib backend
There is an issue reported in Matplotlib (matplotlib/matplotlib#28855) in which use of a config file `~/.ipython/profile_default/ipython_kernel_config.py` containing `c.InteractiveShellApp.matplotlib = 'inline'` results in the default Matplotlib backend being enabled rather than `matplotlib-inline`. I think this has occurred historically in some situations (such as #25) but is now more likely given the recent movement of the backend-handling code from IPython to Matplotlib.

My analysis (https://github.com/matplotlib/matplotlib/issues/28855#issuecomment-2402411376) is that it is a simple fix in matplotlib-inline to allow us to check what the current Matplotlib backend is without automatically enabling the defaults backend if none has yet been specified. I will submit a PR with this fix shortly, when I have performed some comprehensive manual testing that it does not break some other current use case.

### PR DESCRIPTION
**Pull request by ianthomas23**
Fixes #37 and #25.

When importing `backend_inline` the function `_enable_matplotlib_integration()` is automatically called and this checks what the current Matplotlib backend is. Previously calling `matplotlib.get_backend()` if no backend was currently set would as a side-effect force it to be the default backend for that OS rather than leaving it unset. Changing it to `matplotlib.rcParams._get("backend")` avoids the side-effect thus fixing the problem.

Although `rcParams._get` is a private function this is in fact the correct function to use as explained in the Matplotlib source code:
https://github.com/matplotlib/matplotlib/blob/eb812a8e479d0bcf43a30232c31afec78963ed53/lib/matplotlib/__init__.py#L698-L713

To reproduce the original problem and confirm this PR fixes it use the following on the `main` branch and this PR branch:

1. Create file `~/.ipython/profile_default/ipython_kernel_config.py` containing the single line `c.InteractiveShellApp.matplotlib = 'inline'`.
2. Use either `jupyter lab` or `jupyter qtconsole` and run the following code: `import matplotlib.pyplot as plt; plt.plot([1,3,2])`

On `main` branch this uses the wrong Matplotlib backend and on this PR branch it used the correct `inline` backend.

I have manually tested other use cases of using Matplotlib in `ipython` and `jupyter` and it looks like this fix does not introduce any new problems.

### CODE REVIEW

**Comment by ianthomas23** [comment]
The test image changes are on the `main` branch rather than this PR; I have included them here rather than create a separate PR.

**Comment by ianthomas23** [comment]
I've converted this to Draft as there are changes planned in Matplotlib that will make the fix different and better.

**Comment by Carreau** [comment]
Sorry I missed that ping me if this get delayed.

**Comment by Carreau** [comment]
I've made you maintainer to unblock you a bit.

**Pull request merged**
